tox-dev/pyproject-fmt

- .pre-commit-hooks.yaml
*Issue number of the reported bug or feature request: None.
**Describe your changes**
Any description here would be longer than the change itself.
**Testing performed**
Didn't test it at all.
**Additional context**
See 473094a2cdfe84a56f50934da008e32c5b3cf5a3
> docs: corrected hook description

- .readthedocs.yml
- README.md
- docs/changelog.rst
- docs/conf.py
- docs/index.rst
- pyproject.toml
- src/pyproject_fmt/__init__.py
- src/pyproject_fmt/cli.py
- src/pyproject_fmt/formatter/__init__.py
- src/pyproject_fmt/formatter/build_system.py
- src/pyproject_fmt/formatter/pep508.py
- src/pyproject_fmt/formatter/project.py
- src/pyproject_fmt/formatter/util.py
- tox.ini
- whitelist.txt
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Add sphinx documentation build

- docs/changelog.rst
- docs/index.rst
- src/pyproject_fmt/__init__.py
- src/pyproject_fmt/__main__.py
- src/pyproject_fmt/cli.py
- src/pyproject_fmt/formatter/__init__.py
- src/pyproject_fmt/formatter/build_system.py
- src/pyproject_fmt/formatter/config.py
- src/pyproject_fmt/formatter/project.py
- tests/__init__.py
- tests/formatter/conftest.py
- whitelist.txt
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>
> Add programmatic API

- src/pyproject_fmt/cli.py
> Swap tox.ini refs to pyproject.toml

- README.md
this makes finding/adding it quicker
> add pre-commit snippet to readme

- src/pyproject_fmt/formatter/tools.py
- tests/formatter/test_tools.py
> Put setuptools_scm after setuptools

- .pre-commit-config.yaml
- README.md
- pyproject.toml
- src/pyproject_fmt/formatter/util.py
- tests/formatter/test_tools.py
- tox.ini
> Bump deps and tools and fix CI

- .pre-commit-config.yaml
Committed via https://github.com/asottile/all-repos
> Add pyproject-fmt

- pyproject.toml
- tox.ini
Committed via https://github.com/asottile/all-repos
> Bump deps and tools

- .github/workflows/check.yml
- src/pyproject_fmt/formatter/project.py
- tests/formatter/conftest.py
- tests/formatter/test_project.py
- tox.ini
- whitelist.txt
> Generate python version classifiers based on python-requires

- src/pyproject_fmt/formatter/project.py
- tests/formatter/test_project.py
- whitelist.txt
> Keep implementation classifiers

- .pre-commit-config.yaml
- pyproject.toml
- src/pyproject_fmt/formatter/tools.py
- src/pyproject_fmt/formatter/util.py
- tests/formatter/test_tools.py
> Do not crash on out of order tables

- src/pyproject_fmt/formatter/tools.py
- tests/formatter/test_tools.py
This PR adds `autopep8` to the list of tools.
Closes #104
> Add `autopep8`

- pyproject.toml
> feat: include tox.ini in sdist

- .github/workflows/check.yml
- .pre-commit-config.yaml
- .readthedocs.yml
- README.md
- docs/index.rst
- pyproject.toml
- src/pyproject_fmt/cli.py
- src/pyproject_fmt/formatter/config.py
- src/pyproject_fmt/formatter/project.py
- src/pyproject_fmt/formatter/util.py
- tests/formatter/test_project.py
- tests/test_cli.py
- tox.ini
> Ignore failure of tox executable and drop 3.7 

- .pre-commit-config.yaml
- docs/index.rst
- pyproject.toml
- src/pyproject_fmt/__main__.py
- src/pyproject_fmt/cli.py
- src/pyproject_fmt/formatter/build_system.py
- src/pyproject_fmt/formatter/project.py
- src/pyproject_fmt/formatter/tools.py
- src/pyproject_fmt/formatter/util.py
- tests/formatter/test_project.py
- tox.ini
> Fix generating Python version classifiers based on python-requires

- src/pyproject_fmt/formatter/pep508.py
- tests/formatter/test_pep508.py
This method is unused outside of tests.
> Remove normalize_requires method

- tests/formatter/test_pep508.py
I plan to change this method as part of #141 and figured it would be helpful to have a direct test for it.
> Add test for normalize_pep508_array

- src/pyproject_fmt/formatter/tools.py
- tests/formatter/test_tools.py
This adds some more common tools, following the pattern listed in https://github.com/tox-dev/pyproject-fmt/issues/127.
> fix: support more common tools

- src/pyproject_fmt/formatter/tools.py
- tests/formatter/test_tools.py
https://github.com/fpgmaas/deptry
> feat: Add `deptry` tool

- src/pyproject_fmt/cli.py
- src/pyproject_fmt/formatter/config.py
- src/pyproject_fmt/formatter/project.py
- tests/formatter/test_project.py
> Support adding the classifier for the current Python prerelease

- src/pyproject_fmt/formatter/project.py
- tests/formatter/test_project.py
Closes https://github.com/tox-dev/pyproject-fmt/issues/183
> Enforce single line `description`

- .readthedocs.yml
> ci: fix ReadTheDocs

- docs/conf.py
> docs: fix version import

- .readthedocs.yml
Testing the recommended workaround (https://github.com/readthedocs/readthedocs.org/issues/11289) for uv, plus my own possible optimization.
> ci: try uv on readthedocs

- pyproject.toml
Only need to build one wheel, so save time not checking the others.
> ci: reduce time building wheels

- .pre-commit-config.yaml
- pyproject.toml
- src/pyproject_fmt/__main__.py
- src/pyproject_fmt/cli.py
> Pass configuration via separate class

- docs/index.rst
- pyproject.toml
> Pull in upstream fixes and update docs

- pyproject.toml
> Pull in empty sub-tables makes formatting unstable fix

- pyproject.toml
> Fix table expansion leaves behind extra content

- docs/index.rst
- pyproject.toml
- src/pyproject_fmt/cli.py
Close https://github.com/tox-dev/pyproject-fmt-rust/issues/29.
> fix: new column width

- pyproject.toml
- tox.ini
> Fix sorting not using full spec

- docs/index.rst
> Add Philosophy section

- pyproject.toml
- tox.ini
> Fix declare 3.13 support

- pyproject.toml
> Pull in description fix
