docs/changelog.rst, pyproject.toml, src/pyproject_fmt/formatter/pep508.py, tests/formatter/test_pep508.py, tests/formatter/test_project.py, whitelist.txt
*Issue number of the reported bug or feature request: #6*
**Motivation**
Hi @gaborbernat thank you very much for the great (and super useful) project!
While I was working on `ini2toml` I received some feedback in the PyPA discord with people suggesting using single quotes for the requirements that contain double quotes, to prevent `tomlkit` to escape the quotes.
The idea is to have
```toml
dependencies = [
'packaging>=20.0;python_version>"3.4"',
]
```
instead of:
```toml
dependencies = [
"packaging>=20.0;python_version>\"3.4\"",
]
```
(this is more or less the same approach `black` takes, with the difference that literal strings in TOML are more limited than the ones in Python).
Would you consider incorporating this style to `pyproject-fmt`?
**Describe your changes**
- Changed …
=> Improve representation of dependency strings

docs/changelog.rst, src/pyproject_fmt/formatter/build_system.py, src/pyproject_fmt/formatter/project.py, src/pyproject_fmt/formatter/util.py, tests/formatter/test_project.py
Hello, this is a possible approach to fix #11.
The approach I took here was to pass the entire table object to the `order_keys` function, so it can be inspected to determine when it is appropriate (or not) to add an empty line.
I understand that the changes here might not be exactly what you have in mind, so please feel free to close this PR or ask for changes, I will be happy to implement them.
=> Fix invalid newline inside inline-table

docs/index.rst
This PR changes the version of `pyproject-fmt` used in the sample pre-commit hook to the most recent release.
Thank you for making this awesome tool!
=> Update version of `pyproject-fmt` in example pre-commit hook in docs

src/pyproject_fmt/__main__.py
Like tox-ini-fmt, let's only write to the file if the content has changed:
https://github.com/tox-dev/tox-ini-fmt/blob/371d5d59738f8f1fc7c8ebf0b5efbc71788bec1f/src/tox_ini_fmt/__main__.py#L40-L42
```console
$ touch -t 202301011200 pyproject.toml
$ date -r pyproject.toml
Sun Jan  1 12:00:00 EET 2023
$ pyproject-fmt pyproject.toml
no change for pyproject.toml
$ date -r pyproject.toml
Thu Jan 19 16:03:09 EET 2023
```
```console
$ date -r pyproject.toml
Sun Jan  1 12:00:00 EET 2023
$ pyproject-fmt pyproject.toml
no change for pyproject.toml
$ date -r pyproject.toml
Sun Jan  1 12:00:00 EET 2023
```
=> Only write to file if changed

src/pyproject_fmt/formatter/project.py, tests/formatter/test_project.py, whitelist.txt
Fixes https://github.com/tox-dev/pyproject-fmt/issues/55.
Follow the spec by using the `normalize` function in the spec:
https://packaging.python.org/en/latest/specifications/name-normalization/#normalization
Update and add test cases, using `pytest.mark.parametrize`.
=> Follow the package name normalization spec

src/pyproject_fmt/formatter/util.py, tests/formatter/test_tools.py, whitelist.txt
=> Fix unnecessary newline addition on sub-tables

pyproject.toml, src/pyproject_fmt/formatter/project.py, src/pyproject_fmt/formatter/util.py, tests/formatter/test_project.py, whitelist.txt
Right now, pyproject-fmt indents most sections using the `--indent` value (default: 2 spaces), but not the project `classifiers` section.
For example, if I first modify this project's `pyproject.toml` to use four space, then run `pyproject-fmt pyproject.toml`, they're all fixed to two spaces, except for the classifiers:
```diff
--- pyproject.toml
+++ pyproject.toml
@@ -1,8 +1,8 @@
[build-system]
build-backend = "hatchling.build"
requires = [
-    "hatch-vcs>=0.3",
-    "hatchling>=1.13",
+  "hatch-vcs>=0.3",
+  "hatchling>=1.13",
]
[project]
@@ -10,8 +10,8 @@
description = "Format your pyproject.toml file"
readme = "README.md"
keywords = [
-    "format",
-    "pyproject",
+  "format",
+  "pyproject",
]
license.file = "LICENSE.txt"
authors = [{ name = "Bernat Gabor", email = …
```
=> Sort classifiers and respect `--indent`

src/pyproject_fmt/formatter/project.py, tests/formatter/test_project.py
Add support for using PEP440 version specifiers in `requires-python`.  This allows the user to specify multiple bounds, e.g. `<=3.11,!=3.9,>=3.8`.
~~Ref. https://github.com/tox-dev/pyproject-fmt/issues/106, also removes `Only` lines.~~
Big thanks to @tomrtk for helping out.
Fixes #99.
=> feat: allow pep440 version specifiers in requires-python

.github/workflows/check.yml
https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases
The test runs on `3.12.0-rc.1` instead of the current `3.12.0-rc.3` today and `3.12.0` production release tomorrow.
=> GitHub Actions: Autoupgrade to Py3.12 production release

.github/workflows/check.yml, src/pyproject_fmt/formatter/project.py, tests/formatter/test_project.py
Python 3.12 is scheduled to ship tomorrow.  https://docs.python.org/3.12/whatsnew/3.12.html
=> _PY_MAX_VERSION: int = 12

tests/__init__.py, tests/formatter/conftest.py, tests/formatter/test_build_system.py, tests/formatter/test_project.py
This introduces a way to test formatting with a custom config. Once this, or another way to achieve that, is merged, new config options can be tested at this level, such as the one proposed in #141 .
=> Add test for indent at formatter test level

.pre-commit-config.yaml, pyproject.toml
Modernizing the Ruff config a bit. More things are in a .lint namespace now.
=> chore: modernize Ruff config

src/pyproject_fmt/cli.py, src/pyproject_fmt/formatter/build_system.py, src/pyproject_fmt/formatter/config.py, src/pyproject_fmt/formatter/pep508.py, src/pyproject_fmt/formatter/project.py, tests/formatter/test_build_system.py, tests/formatter/test_pep508.py, tests/formatter/test_project.py, tests/test_main.py
Using this option adds compatibility with Dependabot. Without this: Dependabot will bump a package to 1.3.0 and then pyproject-fmt will fail in CI because of the difference between the new and expected package version.
Fixes #141 .
=> Add option to skip normalising requirement versions

src/pyproject_fmt/cli.py
This was just an error by me.
I can add a test if wanted, but I think it isn't the most useful test.
=> Allow --check and --keep-full-version, they are not mutually exclusive

src/pyproject_fmt/formatter/tools.py, tests/formatter/test_tools.py
I scanned most of the repos that I have downloaded at some point for their pyproject.toml tool sections, then looked at every unique tool key. I've added the ones that make sense here (a few projects have their own tool section, but it's not clear it's useful for anyone else, and there were a couple of very general sounding ones that I wasn't sure about like `tool.aliases` in `pylint` that I left off). I also added a couple of other ones I'm familiar with.
=> fix: add more tools

.github/workflows/check.yml, .github/workflows/release.yml, .pre-commit-config.yaml
The 1.6.0 release failed to go out because of an error in the `release.yml`  workflow.
=> Fix the "Release to PyPI" workflow and add check-jsonschema as a pre-commit hook to prevent future errors

docs/index.rst, src/pyproject_fmt/__init__.py, src/pyproject_fmt/formatter/__init__.py, src/pyproject_fmt/formatter/config.py, src/pyproject_fmt/formatter/tools.py, tests/formatter/test_project.py
Closes https://github.com/tox-dev/pyproject-fmt/issues/130
=> Configure pyproject-fmt options from `pyproject.toml` file

src/pyproject_fmt/__main__.py, src/pyproject_fmt/cli.py, tests/test_cli.py
Resolves https://github.com/tox-dev/pyproject-fmt/issues/188
=> Fix missing dependency

docs/index.rst
Re: https://github.com/tox-dev/pyproject-fmt/issues/198#issuecomment-2105993460
Plus slight wording adjustment.
=> Remove outdated YAML example

.github/workflows/check.yml
Noticeably faster if you want it.
=> ci: try uv

src/pyproject_fmt/__main__.py, src/pyproject_fmt/cli.py, tests/test_cli.py
When the input filename is '-', read the toml from stdin and output to stdout.
Closes #238.
=> Allow for reading TOML files from stdin.

.github/workflows/check.yml, .pre-commit-config.yaml, .readthedocs.yml, pyproject.toml, tox.ini
=> Declare 3.13 support

pyproject.toml
> If you're already using a `pyproject.toml` file, we recommend `project.requires-python` instead, as it's based on Python packaging standards, and will be respected by other tools.
https://docs.astral.sh/ruff/settings/#target-version
=> Remove `tool.ruff.target_version`
